export const PROGRAM_CONSTANTS = {
  STRING_COMPRESSION: "STRING_COMPRESSION",
  MAX_PROFIT_STOCS: "MAX_PROFIT_STOCS",
  PALINDROME: "PALINDROME",
  BALANCED_BRACKETS: "BALANCED_BRACKETS",
  MOST_COMMON_WORD: "MOST_COMMON_WORD",
  REMOVE_DUPLICATES: "REMOVE_DUPLICATES",
};
